import { createApp } from "vue";
import router from "./router";
import "prismjs/themes/prism.css";
import "./style.css";
import _ from "prismjs";
import App from "./App.vue";
import TabPreview from "./components/ui/markdown-components/TabPreview.vue";
import Steps from "./components/ui/markdown-components/Steps.vue";
import HeaderDocs from "./components/ui/markdown-components/HeaderDocs.vue";
import EditThisPage from "./components/ui/markdown-components/EditThisPage.vue";
import DocsPage from "./components/ui/markdown-components/DocsPage.vue";
import Preview from "./components/ui/markdown-components/Preview.vue";

const app = createApp(App);
app.component("TabPreview", TabPreview);
app.component("Steps", Steps);
app.component("HeaderDocs", HeaderDocs);
app.component("EditThisPage", EditThisPage);
app.component("DocsPage", DocsPage);
app.component("Preview", Preview);
app.use(router);
app.mount("#app");
